-- Create the AEX_Candidate_Data table with exact schema
CREATE TABLE public."AEX_Candidate_Data" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "Application ID" character varying null,
  "Role Code" character varying null,
  "Candidate Name" character varying null,
  "Candidate Email ID" character varying null,
  "Candidate Contact Number" character varying null,
  "Candidate years of experience" character varying null,
  "Candidate relevant years of experience" character varying null,
  "Notice Period" character varying null,
  "Current CTC" character varying null,
  "Candidate Salary Expectation" character varying null,
  "Current Location" character varying null,
  "Candidate Resume" character varying null,
  "Job Applied" character varying null,
  "Skills" character varying null,
  "Documents" character varying null,
  constraint AEX_Candidate_Data_pkey primary key (id)
);

-- Enable Row Level Security
ALTER TABLE public."AEX_Candidate_Data" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for admin access
CREATE POLICY "Admins can view AEX_Candidate_Data"
ON public."AEX_Candidate_Data"
FOR SELECT
USING (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can insert AEX_Candidate_Data"
ON public."AEX_Candidate_Data"
FOR INSERT
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update AEX_Candidate_Data"
ON public."AEX_Candidate_Data"
FOR UPDATE
USING (public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete AEX_Candidate_Data"
ON public."AEX_Candidate_Data"
FOR DELETE
USING (public.has_role(auth.uid(), 'admin'::app_role));